version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
    open-pull-requests-limit: 10
    labels:
      - dependencies
    commit-message:
      prefix: 'chore'
      include: 'scope'
    groups:
      aws-sdk:
        patterns:
          - '@aws-sdk/*'
          - '@smithy/*'
      dev-dependencies:
        dependency-type: 'development'
        patterns:
          - '@types/*'
          - 'eslint*'
          - 'prettier*'
          - 'typescript*'
          - '@typescript-eslint/*'
          - 'gulp*'
          - 'secretlint*'
          - '@secretlint/*'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - dependencies
      - ci
    commit-message:
      prefix: 'ci'
    groups:
      github-actions:
        patterns: ['*']
